spring.application.name=bajrix-marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/bajrix
spring.datasource.username=postgres
spring.datasource.password=YourNewPasswordHere

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
